---
title: "online question"
output: html_document
date: "2024-09-28"
---


```{r}
setClass("estimator", representation( MPC = "numeric",
                                      H = "numeric", 
                                      x_vector = "numeric",
                                      y_vector = "numeric",
                                      input_argument = "numeric",
                                      data = "matrix"))
                                      

setMethod("initialize", "estimator", function(.Object, MPC, H, x_vector, y_vector, input_argument, data) {
  
    raw_data <- cbind(x_vector,y_vector)
    
    clean_data <- na.omit(raw_data)
  
    data <- matrix(data = NA, nrow=nrow(clean_data),ncol=ncol(clean_data))
      
    data <- clean_data
  
  .Object <- callNextMethod(.Object, MPC=MPC, H=H, x_vector=x_vector, y_vector=y_vector, input_argument=input_argument, data=data)
  
  validObject(.Object)
  
  return(.Object)
  
})

```


```{r}
setGeneric("kernel.smoother", function(object) { standardGeneric("kernel.smoother")})

setMethod("kernel.smoother", signature = "estimator", function (object) {

  j <- length(object@input_argument)
  n <- nrow(object@data)
  
  Input <- object@input_argument
  Data <- object@data
  h <- object@H
    
  for (k in 1:j) {
  
  Upper_Kappa = numeric()
  
  Lower_Kappa = numeric()
    
  for (i in 1:n) {
 
      Upper_Kappa[i]<- Data[i,2]*(dnorm((Input[k]-Data[i,1])/h,0,1)^2)

      Lower_Kappa[i]<- (dnorm((Input[k]-Data[i,1])/h,0,1))^2
  
     }

    object@MPC[k] <- sum(Upper_Kappa)/sum(Lower_Kappa)
  
  }
 
   return(object)
  
})

```


```{r}

x <- runif(100,-3,3)

y <- dnorm(x)

plot(x,y)





vessel <- new("estimator", MPC = numeric(0),H = 2, x_vector = x, y_vector = y, input_argument = seq(-4,4,length.out=500), data = matrix(0))

output <- kernel.smoother(vessel)

show(output)
```

```{r}
setMethod("show", signature = "estimator", function (object){
  cat("output of estimator", object@MPC, "\n")
  plot(x=object@input_argument,y=object@MPC)
  })
```




